### ISSUE TITLE
TypeError: mbr_config.metric_kwargs must be hashable.

### ISSUE THREAD

**Issue by shahzaib-s-warraich** [ZurichNLP/mbr#8]
Hi facing the following issue while reproducing run_experiment.py in bertsch et al:

raise TypeError(f"mbr_config.metric_kwargs must be hashable.") from e
TypeError: mbr_config.metric_kwargs must be hashable.

**Comment by jvamvas** [comment]
Hi @shahzaib-s-warraich,

Thanks for reporting this. I believe this was fixed in the commit https://github.com/ZurichNLP/mbr/commit/67b7074915bb45641aef53104ff6cce002d162c8#diff-fdab01d97e6e64f86fb0c3250c143b0036b9e6f897f04791de85679532fce635L43.

Could you please check out the main branch and try again?
